### ISSUE TITLE
Android 5.1 crash on startup

### ISSUE THREAD

**Issue by PingForward** [zendesk/belvedere#18]
When app starts
java.lang.ClassNotFoundException: Didn't find class "com.zendesk.belvedere.BelvedereFileProvider" 
but this class exist!!

**Comment by schlan** [comment]
Hi @PingForward, are you using proguard in your project? Does it only happen on Android 5.1 devices?

**Comment by schlan** [comment]
Please let me know if you also see that issue in the latest version.

**Comment by iamdeadman** [comment]
Hi, 

Yes facing the same issue here. 
The dependency version I am using is - 
implementation 'com.zendesk.belvedere2:belvedere:2.1.0'

Please find below the crash logs from firebase in case they can help identify and resolve the issue here though I mostly believe this is because the BelvedereFileProvider is not added to multidex-config file and I would have tried to add it there but I do not know the fully qualified classpath of BelvedereFileProvider to be set there if you can help me out with this I can try with multidex config to see if that resolves the issue. 

Log Data -  

Fatal Exception: java.lang.RuntimeException
Unable to get provider zendesk.belvedere.BelvedereFileProvider: java.lang.ClassNotFoundException: zendesk.belvedere.BelvedereFileProvider
android.app.ActivityThread.installProvider (ActivityThread.java:4694)
android.app.ActivityThread.installContentProviders (ActivityThread.java:4321)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:4263)
android.app.ActivityThread.access$1400 (ActivityThread.java:140)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1297)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:174)
android.app.ActivityThread.main (ActivityThread.java:4952)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1027)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:794)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by schlan** [comment]
Hey @iamdeadman, The full package name of the FileProvider is ` zendesk.belvedere.BelvedereFileProvider`. Please let me know if the issues gets resolved by adding it to the multidex config.
